sonar.projectKey=jeewan-platform
sonar.projectName=JEEWAN Anti-Drug Platform
sonar.projectVersion=1.0.0

sonar.sources=backend/auth/app,backend/sos/app,backend/chatbot/app,backend/gamification/app,backend/maps/app,backend/risk/app,backend/admin/app
sonar.tests=backend/tests
sonar.python.version=3.12

sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/migrations/**,**/*.min.js,**/dist/**

# Coverage
sonar.python.coverage.reportPaths=backend/reports/coverage.xml

# Quality Gate
sonar.qualitygate.wait=true
